### PR TITLE
[Infra] Enabel access to the logging service

### PR DESCRIPTION
**Pull request by Rwatana**
## Issue Number
#529 

## Implementation Summary
This pull request modifies the docker-compose setup, ensuring that the frontend service is now properly connected to the logging service’s network, allowing log data to be transmitted smoothly.

## Scope of Impact
Changes will take effect upon redeployment. With this update, the log routing will be adjusted so that logs previously retained in the frontend are now forwarded to the logging service.

## Particular points to check
Verify that the new network configuration doesn’t interfere with existing services or introduce unexpected dependencies. Ensure that the logging service still functions as intended for other parts of the system.

## Test
X-Clone
```
make up
```
Twitter-Clone(TS)
```
➜  ts git:(feature/#529_Enable_access_to_the_logging_service) ✗ d
ocker compose build
docker compose up -d
docker compose exec app bash
```

```
root@290a43ac81c5:/app/twitter# nc -vz rabbitmq 5672
Connection to rabbitmq (172.20.0.5) 5672 port [tcp/amqp] succeeded!
```
Log-service
```
make up
```

## Schedule
Target merge date: 12/21

### CODE REVIEW

**Comment by Rwatana** [comment]
@nayuta-ai 
Please check my code.

**Comment by ryuji0123** [comment]
[Infra] Enabel access to the logging service

[Infra] Enable access to the logging service

**Comment by ryuji0123** [comment]
@Rwatana 
What is the current status of this PR?

**Comment by Rwatana** [comment]
I will close this for now as the frontend is not yet complete.

**Pull request closed without merging**
